Create models
Brabada/FoodPlan pull request #6
Opened 2023-09-21 20:51 UTC by Atmoslayer

Объединил все модельки

2023-09-21 21:21 UTC, Brabada requested changes
Нужен фикс

2023-09-21 21:21 UTC, Brabada commented on baseapp/models.py
> +    price = models.DecimalField(
Лучше сделать цену целочисленной без точек. PositiveIntegerField.

2023-09-21 21:21 UTC, Brabada commented on baseapp/models.py
> +        max_length=200,
200 слишком мало для описания рецепта. И вообще лучше убрать ограничение на кол-во знаков для рецепта.

2023-09-21 21:21 UTC, Brabada commented on baseapp/models.py
> +    is_free = models.BinaryField(
BinaryField для хранения двоичных значений.
BooleanField для True/False

2023-09-21 21:21 UTC, Brabada commented on baseapp/models.py
> +    calories = models.DecimalField(
Вряд ли кто-то считает калории в десятых и сотых. Используй PositiveIntegerField

2023-09-21 21:21 UTC, Brabada commented on baseapp/models.py
> +    price = models.DecimalField(
Обычно ПМ грит, чтобы использовали целочисленное для цен. Но тут смотри сам.

2023-09-21 21:21 UTC, Brabada commented on baseapp/models.py
> +    price = models.DecimalField(
Ругнется ли бд, если попытаться поставить единицу, как требуется в валидации на минимальное значение?

2023-09-21 21:21 UTC, Brabada commented on baseapp/models.py
> +        related_name='dish_items',
мб related_name='dish_ingredient_items'?

2023-09-21 21:21 UTC, Brabada commented on baseapp/models.py
> +        related_name='ingredient_items',
так же поставить related_name=dish_ingredient_items для однородности.

2023-09-21 21:21 UTC, Brabada commented on baseapp/models.py
> +        return f'{self.ingredient.name} для {self.dish.name}.'
Убрать точку

2023-09-21 21:21 UTC, Brabada commented on baseapp/models.py
> +        related_name='type_of_menu',
related_name='menu_categories'

2023-09-21 21:21 UTC, Brabada commented on baseapp/models.py
> +        related_name='type_of_menu',
всё-таки блюдо может отнестись к нескольким категориям меню

2023-09-21 21:21 UTC, Brabada commented on baseapp/models.py
> +    )
добавить class Meta:
        verbose_name = '
        verbose_name_plural = 

    def __str__(self):
        return self.name

2023-09-21 21:21 UTC, Brabada commented on baseapp/models.py
> +        User,
не User, а CustomUser

2023-09-21 21:21 UTC, Brabada commented on baseapp/models.py
> +        related_name='dish_subscriptions',
related_name='subscriptions',

2023-09-21 21:21 UTC, Brabada commented on baseapp/models.py
> +        related_name='allergy_subscriptions',
Почему MealType, а не Allergies?

related_name=subscriptions 
иначе строка доступа к подпискам аллергии будет перегружена: лучше "allergy.subscriptions.all()", чем "allergy.allergy_sub..." и тд.

2023-09-21 21:21 UTC, Brabada commented on baseapp/models.py
> +        return self.user.name
return self.user.email

2023-09-21 21:23 UTC, Atmoslayer commented on baseapp/models.py
> +    price = models.DecimalField(
Брал пример из готового кода. Там использовали такую конструкцию. Я не против использовать целые числа, но если цена будет, например, в долларах, там такой фокус не прокатит

2023-09-21 21:24 UTC, Atmoslayer commented on baseapp/models.py
> +        max_length=200,
Бесконечное количество символов поддерживает только Postgres. Тут надо что-то поставить? 500?

2023-09-21 21:25 UTC, Atmoslayer commented on baseapp/models.py
> +    is_free = models.BinaryField(
Это перепутал, это исправлю

2023-09-21 21:25 UTC, Atmoslayer commented on baseapp/models.py
> +    calories = models.DecimalField(
Наверное, ты прав, подправлю на int

2023-09-21 21:26 UTC, Atmoslayer commented on baseapp/models.py
> +    price = models.DecimalField(
> Ругнется ли бд, если попытаться поставить единицу, как требуется в валидации на минимальное значение?

Нет, единицу забить можно

2023-09-21 21:28 UTC, Brabada commented on baseapp/models.py
> +    price = models.DecimalField(
Вряд ли мы выйдем на международный рынок)

2023-09-21 21:31 UTC, Atmoslayer commented on baseapp/models.py
> +        related_name='dish_subscriptions',
Нельзя указать одно и то же related_name на одну и ту же модель из разных

2023-09-21 21:31 UTC, Brabada commented on baseapp/models.py
> +        max_length=200,
First, just to make sure we’re clear here - setting a max size on the TextField only affects the maximum size of the textarea widget on the page. Django does not enforce any size limit on a TextField in the database. 

Короче говоря, на sqlite3 все работает без ограничителя, данный параметр для TextField влияет на размер текстового поля для ввода текста и всё.

2023-09-21 21:32 UTC, Atmoslayer commented on baseapp/models.py
> +        related_name='allergy_subscriptions',
Это ошибка. Здесь должно быть allergies

2023-09-21 21:37 UTC, Brabada commented on baseapp/models.py
> +        related_name='dish_subscriptions',
> Нельзя указать одно и то же related_name на одну и ту же модель из разных

First, just to make sure we’re clear here - setting a max size on the TextField only affects the maximum size of the textarea widget on the page. Django does not enforce any size limit on a TextField in the database.

2023-09-21 21:39 UTC, leksuss commented on baseapp/models.py
> +        validators=[MinValueValidator(0)],
тут наверно 1 минимальное значение должно быть

2023-09-21 21:40 UTC, Atmoslayer commented on baseapp/models.py
> +        max_length=200,
The maximum length (in characters) of the field. The max_length is enforced at the database level and in Django’s validation using [MaxLengthValidator](https://docs.djangoproject.com/en/4.2/ref/validators/#django.core.validators.MaxLengthValidator). It’s required for all database backends included with Django except PostgreSQL, which supports unlimited VARCHAR columns.

2023-09-21 21:40 UTC, Atmoslayer commented on baseapp/models.py
> +        max_length=200,
Попробую без него сделать и накатить миграцию. Если сработает, то все окей

2023-09-21 21:41 UTC, Atmoslayer commented on baseapp/models.py
> +        related_name='dish_subscriptions',
Этого не допускает сама Джанга 
baseapp.Subscription.allergies: (fields.E304) Reverse accessor 'MealType.subscriptions' for 'baseapp.Subscription.allergies' clashes with reverse accessor for 'baseapp.Subscription.meal_types'.
        HINT: Add or change a related_name argument to the definition for 'baseapp.Subscription.allergies' or 'baseapp.Subscription.meal_types'.
baseapp.Subscription.allergies: (fields.E305) Reverse query name for 'baseapp.Subscription.allergies' clashes with reverse query name for 'baseapp.Subscription.meal_types'.
        HINT: Add or change a related_name argument to the definition for 'baseapp.Subscription.allergies' or 'baseapp.Subscription.meal_types'.
baseapp.Subscription.meal_types: (fields.E304) Reverse accessor 'MealType.subscriptions' for 'baseapp.Subscription.meal_types' clashes with reverse accessor for 'baseapp.Subscription.allergies'.
        HINT: Add or change a related_name argument to the definition for 'baseapp.Subscription.meal_types' or 'baseapp.Subscription.allergies'.
baseapp.Subscription.meal_types: (fields.E305) Reverse query name for 'baseapp.Subscription.meal_types' clashes with reverse query name for 'baseapp.Subscription.allergies'.
        HINT: Add or change a related_name argument to the definition for 'baseapp.Subscription.meal_types' or 'baseapp.Subscription.allergies'.

2023-09-22 14:08 UTC, Brabada approved these changes
оке

2023-09-22 14:08 UTC, Brabada approved these changes
Оке

2023-09-22 16:27 UTC, merged